studentsdb/urls.py
from django.conf.urls import patterns, include,url
from django.contrib import admin
from .settings import MEDIA_ROOT, DEBUG
from students.view.journal import JournalView
from students.view.exams import ExamList,ExamCreate, ExamUpdate, ExamDelete
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView, TemplateView
from students.view.student import stud_add, student_edit, student_delete
from students.view.group import groups_add, groups_edit, groups_delete 
from students.view.logs import logs
from students.view.contact_admin import contact_admin
from django.contrib.auth.decorators import login_required
from registration.backends.default import views as registration_views
from login.views import user_edit





js_info_dict = {
'packages': ('students',),
}

urlpatterns = patterns('',
# Students urls
url(r'^$', 'students.view.student.students_list', name='main'),
url(r'^stud_add$', login_required(stud_add), name='s_add'),
url(r'^students/(?P<pk>\d+)/edit/$',login_required(student_edit),
name='students_edit'),
url(r'^students/(?P<pk>\d+)/delete/$',login_required(student_delete),name='students_delete'),
#journal
url(r'^journal/(?P<pk>\d+)?/?$', JournalView.as_view(), name='journal'),
#Groups urls
url(r'^grup$', 'students.view.groups.grup', name='groups'),
url(r'^groups_add$', 'students.view.group.groups_add', name='groups_add'),
url(r'^groups/(?P<pk>\d+)/edit/$',
'students.view.group.groups_edit', name='groups_edit'),
url(r'^groups/(?P<pk>\d+)/delete/$',
'students.view.group.groups_delete', name='groups_delete'),
url(r'^groups/(?P<pk>\d+)/one/$',
'students.view.group.groups_one', name='groups_one'),
url(r'^admin/', include(admin.site.urls)),
#exams url
url(r'^exams$', ExamList.as_view(), name='exams'),
url(r'^exam_add$', login_required(ExamCreate.as_view()), name='exam_add'),
url(r'^exams/(?P<pk>\d+)/edit/$', login_required(ExamUpdate.as_view()), name='exam_edit'),
url(r'^exams/(?P<pk>\d+)/delete/$', login_required(ExamDelete.as_view()), name='exam_delete'),
#logs
url(r'^logs$', login_required(logs), name='logs'),
# Contact Admin Form
url(r'^contact-admin/$', login_required(contact_admin),
name='contact_admin'),
#i18n of js
url(r'^jsi18n.js$', 'django.views.i18n.javascript_catalog', js_info_dict),

# User Related urls
url(r'^users/profile/$', login_required(TemplateView.as_view(
template_name='registration/profile.html')), name='profile'),
url(r'^users/logout/$', auth_views.logout, kwargs={'next_page': 'main'}, name='auth_logout'),
url(r'^register/complete/$', TemplateView.as_view(template_name='registration/confirm_email.html'), name='registration_complete'),
url(r'^users/', include('registration.backends.default.urls', namespace='users')),
url(r'^users/activate/(?P<activation_key>\w+)/$', registration_views.ActivationView.as_view(),
name='registration_activate'),
url(r'^users/activate/complete/$',
TemplateView.as_view(template_name='registration/activation_complete.html'),
name='registration_activation_complete'),
url(r'^users_list$', 'log.views.users_list', name='users_list'),
url(r'^users/(?P<pk>\d+)/one/$',
'log.views.users_one', name='users_one'),
url(r'^prof/(?P<pk>\d+)/edit$', 'log.views.user_edit', name='prof_edit'),
url(r'^user/(?P<pk>\d+)/edit$', 'log.views.user_one_edit', name='user_edit'),


# Social Auth Related urls
url('^social/', include('social.apps.django_app.urls', namespace ='social')),
)

if DEBUG:
 # serve files from media folder
 urlpatterns += patterns('',
 url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
 'document_root': MEDIA_ROOT}))

log/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

class StProfile(models.Model):


  user = models.OneToOneField(User)
  class Meta(object):
    verbose_name = _(u"User Profile")

  mobile_phone = models.CharField(
    max_length=12,
    blank=True,
    verbose_name=_(u"Mobile Phone"),
  )
  lang = models.CharField(
    max_length=12,
    blank=True,
    verbose_name=_(u"lang"),
  )
  def __unicode__(self):
    return self.user.username

students/models/exam.py
from django.utils.translation import ugettext_lazy as _
from django.db import models
class Exam(models.Model):
  """Exam Model"""
  class Meta(object):
    verbose_name = _(u"Exam")
    verbose_name_plural = _(u"Exams")
  title = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"name"))
  group = models.ForeignKey('Group',
    verbose_name=_(u'Group'),
    blank=False,
    null=True,)

  date = models.DateField(
    blank=True,
    verbose_name=_(u"dates"))
  def __unicode__(self):
    return u"%s %s" % (self.title, self.group)

students/models/group.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
class Group(models.Model):
  """Group Model"""
  class Meta(object):
    verbose_name = _(u"group")
    verbose_name_plural = _(u"groups")
  title = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"name"))
  leader = models.OneToOneField('Student',
    verbose_name=_(u"leader"),
    blank=True,
    null=True,
    on_delete=models.SET_NULL)
  notes = models.TextField(
    blank=True,
    verbose_name=_(u"Additional notes"))
  def __unicode__(self):
    return u"%s" % (self.title,)

students/models/log.py
# -*- coding: utf-8 -*-
from django.db import models

students/models/monthjournal.py
from django.utils.translation import ugettext_lazy as _
from django.db import models
class MonthJournal(models.Model):
  
    class Meta:
      verbose_name = _(u'Monthly journal')
      verbose_name_plural = _(u'Monthly journals')
      
    student = models.ForeignKey('Student',
      verbose_name=_(u'Student'),
      blank=False,
      unique_for_month='date')
    date = models.DateField(
      verbose_name=_(u'Date'),
      blank=False)
    local_vars = locals()
    for num in range(1, 32):
      local_vars.update({'present_day'+str(num) : models.BooleanField(default=False)})
   
    def __unicode__(self):
      return u'%s: %d, %d' % (self.student.last_name, self.date.month,
        self.date.year)


class logentry(models.Model):
  level = models.CharField(
    max_length=20,
    blank=False)
  asctime = models.DateTimeField(
    blank=False,
    null=True)
  module = models.CharField(
    max_length=100,
    blank=False,)
  message = models.TextField(
    blank=False,)
  def __unicode__(self):
    return u"%s %s %s %s" % (self.level, self.asctime, self.module, self.message)

students/models/student.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
# Create your models here.
class Student(models.Model):
  #Student Model
  class Meta(object):
    verbose_name = _(u"Student")
    verbose_name_plural = _(u"Students")
  first_name = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"first_name"))
  last_name = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"last_name"))
  middle_name = models.CharField(
    max_length=256,
    blank=True,
    verbose_name=_(u"surname"),
    default='')
  birthday = models.DateField(
    blank=False,
    verbose_name=_(u"birthday"),
    null=True)
  photo = models.ImageField(
    blank=True,
    verbose_name=_(u"photo"),
    null=True)
  ticket = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"ticket"))
  student_group_id = models.ForeignKey('Group',
    verbose_name=_(u"group"),
    blank=False,
    null=True,
    on_delete=models.PROTECT)
  notes = models.TextField(
    blank=True,
    verbose_name=_(u"Additional notes"))
  
  def __unicode__(self):
    return u"%s %s" % (self.first_name, self.last_name)

log/views.py
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime
from django.contrib import messages
from PIL import Image
from django.contrib.auth.decorators import login_required








def users_list(request):
	users = User.objects.all()
	return render(request, 'users_list.html',
    {'users': users})







def users_one(request, pk):
   use = User.objects.get(id=pk)
   return render(request, 'user_one_profile.html',
   {'user_one': use})





def user_edit(request, pk):
    use = User.objects.get(pk=pk)
    
    if request.method == "POST":
      data = User.objects.get(pk=pk)
      if request.POST.get('add_button') is not None:

        errors = {}

        username = request.POST.get('username', '').strip()
        if not username:
          errors['username'] = _(u"Name is mandatory.")
        else:
          data.username = username

        password = request.POST.get('password', '').strip()
        if not password:
          errors['password'] = _(u"Name is mandatory.")
        else:
          data.password = password

        email = request.POST.get('email', '').strip()
        if not email:
          errors['email'] = _(u"Name is mandatory.")
        else:
          data.email = email

        if not errors:
          
          data.save()
          return HttpResponseRedirect( u'%s?status_message=%s'  % (reverse('users_list'), _(u'User edited succefully')))
        else:
          # render form with errors and previous user input
          return render(request, 'user_edit.html',
          {'pk': pk,'errors': errors})
      elif request.POST.get('cancel_button') is not None:
        # redirect to home page on cancel button
        return HttpResponseRedirect( u'%s?status_message=%s' % (reverse('users_list'), _('Editing user canceled')))
    else:
     # initial form render
     return render(request, 'user_edit.html',
     {'use': use, 'pk': pk})






@login_required
def user_one_edit(request, pk):
    use = User.objects.get(pk=pk)
    
    if request.method == "POST":
      data = User.objects.get(pk=pk)
      if request.POST.get('add_button') is not None:

        errors = {}

        username = request.POST.get('username', '').strip()
        if not username:
          errors['username'] = _(u"Name is mandatory.")
        else:
          data.username = username

        password = request.POST.get('password', '').strip()
        if not password:
          errors['password'] = _(u"Name is mandatory.")
        else:
          data.password = password

        email = request.POST.get('email', '').strip()
        if not email:
          errors['email'] = _(u"Name is mandatory.")
        else:
          data.email = email

        lang = request.POST.get('lang', '').strip()
        if not lang:
          errors['lang'] = _(u"Language is mandatory")
        else:
          User.stprofile.lang = lang

        if not errors:
          
          data.save()
          return HttpResponseRedirect( u'%s?status_message=%s'  % (reverse('users_list'), _(u'User edited succefully')))
        else:
          # render form with errors and previous user input
          return render(request, 'user_edit.html',
          {'pk': pk,'errors': errors})
      elif request.POST.get('cancel_button') is not None:
        # redirect to home page on cancel button
        return HttpResponseRedirect( u'%s?status_message=%s' % (reverse('users_list'), _('Editing user canceled')))
    else:
     # initial form render
     return render(request, 'user_one_edit.html',
     {'use': use, 'pk': pk})

students/templates/students/exam_add.html
{% extends "students/base.html" %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% block meta_title %}{% endblock meta_title %}
{% block title %}Додавання іспиту{% endblock title %}
{% block status_message %}
{% if errors %}
<div class="alert alert-warning" role="alert">
Будь-ласка, виправте наступні помилки
</div>
{% endif %}
{% endblock status_message %}
{% block content %}
{% crispy form %}
Поля, позначені  зірочкою,  обовязкові  для  заповнення!
{% endblock content %}

students/templates/students/exam_delete.html
{% extends "students/base.html" %}
{% load static from staticfiles %}
{% block meta_title %}Видалити групу{% endblock meta_title %}
{% block title %}Видалити іспит{% endblock title %}
{% block content %}
<form action="" method="post">
{% csrf_token %}
<p>Ви дійсно хочете видалити групу "{{ object }}"?</p>
<input type="submit" value="Так" name="delete_button"
class="btn btn-danger" />
<input type="submit" value="Ні" name="no_delete_button"
class="btn btn-danger" /><br /><br />
</form>
{% endblock content %}

students/templates/students/exams.html
{% extends "students/base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% block meta_title %}{% trans "students" %}{% endblock meta_title %}
{% block title %}{% trans "Base of students" %}{% endblock title %}
{% block content %}
{% if user.is_authenticated %}
<a href="{% url "exam_add" %}" class="btn btn-primary">{% trans "add exam" %}</a>
{% endif %}
<!-- Start Students Listing -->
<table class="table">

{% with order_by=request.GET.order_by reverse=request.GET.reverse %}
<thead>
<tr>
<th>
<a href="{% url "exams" %}?order_by=#{% if order_by == '#' and reverse != '1' %}&amp;reverse=1{% endif %}">
#
{% if order_by == '#' and reverse != '1' %}&uarr;
{% elif order_by == '#' and reverse == '1' %}&darr;
{% endif %}
</a>
</th>
<th>
<a href="{% url "exams" %}?order_by=title{% if order_by == 'title' and reverse != '1' %}&amp;reverse=1{% endif %}">
{% trans "name" %}
{% if order_by == 'title' and reverse != '1' %}&uarr;
{% elif order_by == 'title' and reverse == '1' %}&darr;
{% endif %}
</a>
</th>
<th>
<a href="{% url "exams" %}?order_by=group{% if order_by == 'group' and reverse != '1' %}&amp;reverse=1{% endif %}">
{% trans "group" %}
{% if order_by == 'group' and reverse != '1' %}&uarr;
{% elif order_by == 'group' and reverse == '1' %}&darr;
{% endif %}
</th>
<th>
<a href="{% url "exams" %}?order_by=date{% if order_by == 'date' and reverse != '1' %}&amp;reverse=1{% endif %}">
{% trans "date" %}
{% if order_by == 'date' and reverse != '1' %}&uarr;
{% elif order_by == 'date' and reverse == '1' %}&darr;
{% endif %}
</th>
{% if user.is_authenticated %}
<th>{% trans "actions" %}</th>
{% endif %}
</tr>
</thead>
{% endwith %}

<tbody>
{% for exam in exams %}
<tr>
<td>{{ forloop.counter }}</td>
<td><a href="{% url "exam_edit" exam.id %}">{{ exam.title }}</td>
<td><a href="{% url "exam_edit" exam.id %}">{{ exam.group }}</td>
<td><a href="{% url "exam_edit" exam.id %}">{{ exam.date }}</td>
<td>
{% if user.is_authenticated %}
<div class="btn-group">
<button type="button" class="btn btn-default dropdown-toggle"
data-toggle="dropdown">{% trans "action" %}
<span class="caret"></span>
</button>
<ul class="dropdown-menu" role="menu">
<li><a href="{% url "exam_edit" exam.id %}">{% trans "edit" %}</a></li>
<li><a href="{% url "exam_delete" exam.id %}">{% trans "delete" %}</a></li>
</ul>
</div>
{% endif %}
</td>
</tr>
{% endfor %}
</tbody>
</table>
<!-- End Students Listing -->
{% with object_list=exams %}
{% include "students/pagination.html" %}
{% endwith %}
{% endblock content %}

students/templates/students/groups_add.html
{% extends "students/base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% block meta_title %}{% trans "students" %}{% endblock meta_title %}
{% block title %}{% trans "adding group" %}{% endblock title %}
{% block status_message %}
{% if errors %}
<div class="alert alert-warning" role="alert">
{% trans "Please, correct next errors!" %}
</div>
{% endif %}
{% endblock status_message %}
{% block content %}
<form action="{% url "groups_add" %}" method="post"
enctype="multipart/form-data" role="form" class="form-horizontal">
{% csrf_token %}
<div class="form-group {% if errors.title %}has-error{% endif%}">
<label for="title" class="col-sm-2 control-label">{% trans "name of group" %}*</label>
<div class="col-sm-10">
<input type="text" value="{{ request.POST.title }}"
name="title" id="title" class="form-control" />
<span class="help-block">{{ errors.title }}</span>
</div>
</div>


<div class="form-group {% if errors.notes %}has-error{% endif%}">
<label for="notes" class="col-sm-2 control-label">{% trans "additional notes" %}</label>
<div class="col-sm-10">
<textarea name="notes" id="notes" class="form-control"></textarea>
</div>
</div>
<div class="form-group">
<label class="col-sm-2 control-label"></label>
<div class="col-sm-10">
<input type="submit" value="{% trans "add" %}" name="add_button"
class="btn btn-primary" />
<button type="submit" name="cancel_button"
class="btn btn-link">{% trans "cancel" %}</button>
</div>
</div>
</form>
{% trans "Fields marked with an asterisk are obligatory for filling" %}!
{% endblock content %}

students/templates/students/groups_one_null.html
{% extends "students/base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% block meta_title %}{% trans "students" %}{% endblock meta_title %}
{% block title %} {% trans "group" %} {{group.title}} {% trans "dont contains student" %}{% endblock title %}
{% block content %}
{% endblock content %}

students/templates/students/students_add_edit.html
{% extends "students/base.html" %}
{% load i18n %}
{% trans "students" %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% block meta_title %}
{% trans "students" %}
{% endblock meta_title %}
{% block title %}
{% if student %}
<div id="title_form_edit">{% trans "editing of student" %}  {{student.first_name}} {{student.last_name}}</div>
{% else %}
<div id="title_form_add">{% trans "adding of students" %}</div>
{% endif %}
{% endblock title %}
{% block status_message %}
{% if errors %}
<div class="alert alert-warning" role="alert">
{% trans "please, correct next errors!" %}
</div>
{% endif %}
{% endblock status_message %}
{% block content %}
<form enctype="multipart/form-data" class="form-horizontal"
{% if student %}
 action="{% url "students_edit" pk %}" 
 {% else %}
 action="{% url "s_add" %}"
 {% endif %}
 method="post">
    {% csrf_token %}
    <div class="form-group{% if errors.first_name %} has-error{% endif %}">
        <label for="" class="control-label col-sm-2">{% trans "first name" %}*</label>
        <div class="col-sm-10">
        {% if student %}
            <input type="text" class="form-control" name="first_name" id="first_name" value="{{student.first_name}}">
        {% else %}
           <input type="text" value="{{ request.POST.first_name }}"
           name="first_name" id="first_name" class="form-control" />
        {% endif %}
            <span class="help-block"> {{ errors.first_name }}</span>
        
        </div>
    </div>
    <div class="form-group{% if errors.last_name %} has-error{% endif %}">
        <label for="" class="control-label col-sm-2">{% trans "last name" %}*</label>
        <div class="col-sm-10">
        {% if student %}
            <input type="text" class="form-control" name="last_name" id="last_name" value="{{student.last_name}}">
        {% else %}
            <input type="text" value="{{ request.POST.last_name }}"
            name="last_name" id="last_name" class="form-control" /> 
        {% endif %}
            <span class="help-block"> {{ errors.last_name }}</span>
        </div>
    </div>
    <div class="form-group">
        <label for="" class="control-label col-sm-2">{% trans "surname" %}</label>
        <div class="col-sm-10">
        {% if student %}
            <input type="text" class="form-control" name="middle_name" id="middle_name" value="{{student.middle_name}}">
        {% else %}
            <input type="text" value="{{ request.POST.middle_name }}"
            name="middle_name" id="middle_name" class="form-control" />
        {% endif %}
            <span class="help-block"></span>
        </div>
    </div>
    <div class="form-group{% if errors.birthday %} has-error{% endif %}">
        <label for="" class="control-label col-sm-2">{% trans "birthday" %}*</label>
        <div class="col-sm-10">
        {% if student %}
            <input type="text" class="dateinput form-control" name="birthday" id="id_birthday" value="{{student.birthday|date:"Y-m-d"}}" >
        {% else %}
            <input type="text" class="dateinput form-control" value="{{ request.POST.birthday }}"
            name="birthday" id="birthday" class="form-control"
            placeholder="Напр. 1984-12-30" />
        {% endif %}
            <span class="help-block"> {{ errors.birthday }}</span>
        </div>
    </div>
    <div class="form-group{% if errors.photo %} has-error{% endif %}">
        <label for="" class="control-label col-sm-2">{% trans "photo" %}</label>
        {% if student %}
        <div class="col-sm-10">
            {% if student.photo %}
                 <a href="{{student.photo.url}}">{{student.photo}}</a>
                <input type="checkbox" name="photo"> {% trans "delete" %}    
            {% endif %}
            <input class="form-control" type="file" name="photo" id="photo" value="">
            <span class="help-block"> {{ errors.photo }}</span>
        </div>
        {% else %}
         <div class="col-sm-10">
            <input type="file" value="" name="photo" id="photo" class="form-control" />
             <span class="help-block">{{ errors.photo }}</span>
         </div>
         {% endif %}
    </div>
    <div class="form-group{% if errors.ticket %} has-error{% endif %}">
        <label for="" class="control-label col-sm-2">{% trans "ticket" %}*</label>
        <div class="col-sm-10">
        {% if student %}
            <input type="text" class="form-control" name="ticket" id="ticket" value="{{student.ticket}}">
        {% else %}
            <input type="text" value="{{ request.POST.ticket }}"
            name="ticket" id="ticket" class="form-control" />
        {% endif %}
            <span class="help-block"> {{ errors.ticket }}</span>
        </div>
    </div>
    <div class="form-group{% if errors.student_group_id %} has-error{% endif %}">
        <label for="" class="control-label col-sm-2">{% trans "group" %}*</label>
        {% if student %}
        <div class="col-sm-10">
            <select class="form-control" name="student_group_id" id="student_group_id">
                <option value=""> {% trans "select group" %}</option>
                {% for group in groups %}
                    <option value="{{ group.id }}" {% if group.id == student.student_group_id.id %}selected="1"{% endif %}> {{ group.title }}</option>
                {% endfor %}
            </select>
            <span class="help-block"> {{ errors.student_group_id }}</span>
        </div>
        {% else %}
        <div class="col-sm-10">
           <select name="student_group_id" id="student_group_id" class="form-control"><option value="">{% trans "select group" %}</option>
           {% for group in groups %}
           <option value="{{ group.id }}" {% if group.id == request.POST.student_group_id|add:0 %}selected="1"{% endif %}>{{ group.title }}</option>
           {% endfor %}
           </select>
           <span class="help-block">{{ errors.student_group_id }}</span>
           </div>
        {% endif %}
    </div>
    <div class="form-group">
        <label for="" class="control-label col-sm-2">{% trans "additional information" %}</label>
        {% if student %}
        <div class="col-sm-10">
            <textarea name="notes" id="notes" class="form-control">{{student.notes}}</textarea>
        </div>
        {% else %}
        <div class="col-sm-10">
          <textarea name="notes" id="notes" class="form-control"></textarea>
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        <label for="" class="control-label col-sm-2"></label>
        <div class="col-sm-10">
        {% if student %}
            <input class="btn btn-primary" type="submit" value="Зберегти" name="add_button"/>
            <button class="btn btn-link" type="submit" name="cancel_button">{% trans "cancel" %}</button>
        {% else %}
            <input type="submit" value="{% trans "add" %}" name="add_button"
            class="btn btn-primary" />
            <button type="submit" name="cancel_button"
            class="btn btn-link">{% trans "cancel" %}</button>
        {% endif %}
        </div>
    </div>
</form>
{% trans "Fields marked with an asterisk are obligatory for filling" %}
{% endblock content %}

students/templates/students/students_edit.html
{% extends "students/base.html" %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% block meta_title %}Студенти{% endblock meta_title %}
{% block title %}Редагування студента  {{student.first_name}} {{student.last_name}}{% endblock title %}
{% block status_message %}
{% if errors %}
<div class="alert alert-warning" role="alert">
Будь-ласка, виправте наступні помилки
</div>
{% endif %}
{% endblock status_message %}
{% block content %}
<form enctype="multipart/form-data" class="form-horizontal" action="{% url "students_edit" pk %}" method="post">
    {% csrf_token %}
    <div class="form-group{% if errors.first_name %} has-error{% endif %}">
        <label for="" class="control-label col-sm-2">Імʼя*</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="first_name" id="first_name" value="{{student.first_name}}">
            <span class="help-block"> {{ errors.first_name }}</span>
        </div>
    </div>
    <div class="form-group{% if errors.last_name %} has-error{% endif %}">
        <label for="" class="control-label col-sm-2">Прізвище*</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="last_name" id="last_name" value="{{student.last_name}}">
            <span class="help-block"> {{ errors.last_name }}</span>
        </div>
    </div>
    <div class="form-group">
        <label for="" class="control-label col-sm-2">По-батькові</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="middle_name" id="middle_name" value="{{student.middle_name}}">
            <span class="help-block"></span>
        </div>
    </div>
    <div class="form-group{% if errors.birthday %} has-error{% endif %}">
        <label for="" class="control-label col-sm-2">Дата народження*</label>
        <div class="col-sm-10">
            <input type="text" class="dateinput form-control" name="birthday" id="id_birthday" value="{{student.birthday|date:"Y-m-d"}}" >
            <span class="help-block"> {{ errors.birthday }}</span>
        </div>
    </div>
    <div class="form-group{% if errors.photo %} has-error{% endif %}">
        <label for="" class="control-label col-sm-2">Фото</label>
        <div class="col-sm-10">
            {% if student.photo %}
                Наразі: <a href="{{student.photo.url}}">{{student.photo}}</a>
                <input type="checkbox" name="photo"> Видалити    
            {% endif %}
            <input class="form-control" type="file" name="photo" id="photo" value="">
            <span class="help-block"> {{ errors.photo }}</span>
        </div>
    </div>
    <div class="form-group{% if errors.ticket %} has-error{% endif %}">
        <label for="" class="control-label col-sm-2">Білет*</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="ticket" id="ticket" value="{{student.ticket}}">
            <span class="help-block"> {{ errors.ticket }}</span>
        </div>
    </div>
    <div class="form-group{% if errors.student_group_id %} has-error{% endif %}">
        <label for="" class="control-label col-sm-2">Група*</label>
        <div class="col-sm-10">
            <select class="form-control" name="student_group_id" id="student_group_id">
                <option value=""> Оберіть групу</option>
                {% for group in groups %}
                    <option value="{{ group.id }}" {% if group.id == student.student_group_id.id %}selected="1"{% endif %}> {{ group.title }}</option>
                {% endfor %}
            </select>
            <span class="help-block"> {{ errors.student_group_id }}</span>
        </div>
    </div>
    <div class="form-group">
        <label for="" class="control-label col-sm-2">Додаткова інформація</label>
        <div class="col-sm-10">
            <textarea name="notes" id="notes" class="form-control">{{student.notes}}</textarea>
        </div>
    </div>
    <div class="form-group">
        <label for="" class="control-label col-sm-2"></label>
        <div class="col-sm-10">
            <input class="btn btn-primary" type="submit" value="Зберегти" name="add_button"/>
            <button class="btn btn-link" type="submit" name="cancel_button">Скасувати</button>
        </div>
    </div>
</form>
Поля, позначені  зірочкою,  обовязкові  для  заповнення!
{% endblock content %}